
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Coding\Python\StuManSys\build\assets\frame14")
def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def HomePage(): 
    from Login import LoginPage
    from RankingHomePage import RankingHomePage
    from StudentHomePage import StudentHomePage
    from TeacherHomePage import TeacherHomePage


    def logout_clicked():
        window.destroy()
        LoginPage()
    def student_clicked():
        window.destroy()
        StudentHomePage()
    def teacher_clicked():
        window.destroy()
        TeacherHomePage()
    def ranking_clicked():
        window.destroy()
        RankingHomePage()


    window = Tk()

    window.geometry("934x554")
    window.configure(bg = "#979FB2")


    canvas = Canvas(
        window,
        bg = "#979FB2",
        height = 554,
        width = 934,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
  



    image_image_4 = PhotoImage(
        file=relative_to_assets("image_4.png"))
    image_4 = canvas.create_image(
        467.0,
        277.0,
        image=image_image_4
    )

    image_image_5 = PhotoImage(
        file=relative_to_assets("image_5.png"))
    image_5 = canvas.create_image(
        466.0,
        277.0,
        image=image_image_5
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: logout_clicked(),
        relief="flat"
    )
    button_4.place(
        x=736.0,
        y=46.0,
        width=154.736328125,
        height=63.0
    )

    image_image_6 = PhotoImage(
        file=relative_to_assets("image_6.png"))
    image_6 = canvas.create_image(
        190.0,
        387.0,
        image=image_image_6
    )

    image_image_7 = PhotoImage(
        file=relative_to_assets("image_7.png"))
    image_7 = canvas.create_image(
        464.0,
        389.0,
        image=image_image_7
    )

    image_image_8 = PhotoImage(
        file=relative_to_assets("image_8.png"))
    image_8 = canvas.create_image(
        466.0,
        78.0,
        image=image_image_8
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets("button_5.png"))
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: student_clicked(),
        relief="flat"
    )
    button_5.place(
        x=95.0,
        y=159.0,
        width=198.0,
        height=96.0
    )

    button_image_6 = PhotoImage(
        file=relative_to_assets("button_6.png"))
    button_6 = Button(
        image=button_image_6,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: teacher_clicked(),
        relief="flat"
    )
    button_6.place(
        x=368.0,
        y=159.0,
        width=198.0,
        height=96.0
    )

    button_image_7 = PhotoImage(
        file=relative_to_assets("button_7.png"))
    button_7 = Button(
        image=button_image_7,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: ranking_clicked(),
        relief="flat"
    )
    button_7.place(
        x=641.0,
        y=159.0,
        width=198.0,
        height=96.0
    )

    image_image_9 = PhotoImage(
        file=relative_to_assets("image_9.png"))
    image_9 = canvas.create_image(
        730.0,
        401.0,
        image=image_image_9
    )
    window.resizable(False, False)
    window.mainloop()


