
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Coding\Python\StuManSys\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("934x554")
window.configure(bg = "#979FB2")


canvas = Canvas(
    window,
    bg = "#979FB2",
    height = 554,
    width = 934,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    467.0,
    277.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    467.0,
    277.0,
    image=image_image_2
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    582.5,
    259.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FBFAFA",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=407.0,
    y=241.0,
    width=351.0,
    height=34.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    582.5,
    324.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FBFAFA",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=407.0,
    y=306.0,
    width=351.0,
    height=34.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    467.0,
    145.0,
    image=image_image_3
)

canvas.create_text(
    167.0,
    128.0,
    anchor="nw",
    text="STUDENT MANAGEMENT SYSTEM",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    405.0,
    217.0,
    anchor="nw",
    text="Email",
    fill="#000000",
    font=("Inter", 18 * -1)
)

canvas.create_text(
    405.0,
    282.0,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("Inter", 18 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=393.0,
    y=377.0,
    width=381.0,
    height=47.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    260.0,
    325.0,
    image=image_image_4
)
window.resizable(False, False)
window.mainloop()
