
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Coding\Python\StuManSys\build\assets\frame8")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("934x554")
window.configure(bg = "#979FB2")


canvas = Canvas(
    window,
    bg = "#979FB2",
    height = 554,
    width = 934,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    467.0,
    277.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    466.0,
    277.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    466.0,
    66.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    467.0,
    277.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    466.0,
    276.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    466.0,
    66.0,
    image=image_image_6
)

canvas.create_text(
    51.0,
    108.0,
    anchor="nw",
    text="First Name",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    614.0,
    108.0,
    anchor="nw",
    text="Ranking",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    321.0,
    108.0,
    anchor="nw",
    text="Last Name",
    fill="#000000",
    font=("Inter", 28 * -1)
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    467.0,
    151.00000001575154,
    image=image_image_7
)

canvas.create_text(
    89.0,
    209.0,
    anchor="nw",
    text="John",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    368.0,
    206.0,
    anchor="nw",
    text="Smith",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    89.0,
    295.0,
    anchor="nw",
    text="John",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    368.0,
    292.0,
    anchor="nw",
    text="Smith",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    89.0,
    381.0,
    anchor="nw",
    text="John",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    368.0,
    378.0,
    anchor="nw",
    text="Smith",
    fill="#000000",
    font=("Inter", 28 * -1)
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    478.99969482421875,
    252.501220703125,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    479.0,
    352.0,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    746.0,
    197.0,
    image=image_image_10
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    767.0,
    292.0,
    image=image_image_11
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    747.0,
    425.0,
    image=image_image_12
)
window.resizable(False, False)
window.mainloop()
