
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Coding\Python\StuManSys\build\assets\frame11")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("934x554")
window.configure(bg = "#979FB2")


canvas = Canvas(
    window,
    bg = "#979FB2",
    height = 554,
    width = 934,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    467.0,
    277.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    466.0,
    277.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    466.0,
    66.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    467.0,
    277.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    466.0,
    277.0,
    image=image_image_5
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=43.0,
    y=45.0,
    width=154.736328125,
    height=63.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=627.0,
    y=402.0,
    width=253.0,
    height=63.0
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    469.0,
    66.0,
    image=image_image_6
)

canvas.create_text(
    338.0,
    42.0,
    anchor="nw",
    text="Update Teacher",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    59.0,
    124.0,
    anchor="nw",
    text="ID: ",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    343.0,
    124.0,
    anchor="nw",
    text="First Name: ",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    59.0,
    243.0,
    anchor="nw",
    text="Email:",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    59.0,
    368.0,
    anchor="nw",
    text="Phone Number:",
    fill="#000000",
    font=("Inter", 28 * -1)
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    469.0,
    311.0,
    image=image_image_7
)

canvas.create_text(
    627.0,
    124.0,
    anchor="nw",
    text="Last Name: ",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    627.0,
    243.0,
    anchor="nw",
    text="Subject",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    72.0,
    165.0,
    anchor="nw",
    text="123123123",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    358.0,
    165.0,
    anchor="nw",
    text="John",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    644.0,
    165.0,
    anchor="nw",
    text="Smith",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    644.0,
    284.0,
    anchor="nw",
    text="CS",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    72.0,
    284.0,
    anchor="nw",
    text="johnsmith@gmail.com",
    fill="#000000",
    font=("Inter", 28 * -1)
)

canvas.create_text(
    72.0,
    410.0,
    anchor="nw",
    text="123123123123123",
    fill="#000000",
    font=("Inter", 28 * -1)
)
window.resizable(False, False)
window.mainloop()
